-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 17:13:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaConstancias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaConstancias` ;

-- -----------------------------------------------------
-- Schema SistemaConstancias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaConstancias` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `SistemaConstancias` ;

-- -----------------------------------------------------
-- Table `Constancia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Constancia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Constancia` (
  `idConstancia` INT NOT NULL AUTO_INCREMENT,
  `docenteSolicitud` INT NOT NULL,
  `fechaSolicitud` DATETIME NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `tipo` NVARCHAR(30) NOT NULL,
  `idFirmaDigital` INT NOT NULL,
  `idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idConstancia`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ConstanciaParticipante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConstanciaParticipante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ConstanciaParticipante` (
  `idConstancia` INT NOT NULL,
  `idParticipante` INT NOT NULL,
  PRIMARY KEY (`idConstancia`, `idParticipante`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Docente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Docente` (
  `idDocente` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` NVARCHAR(50) NOT NULL,
  `usuario` NVARCHAR(50) NOT NULL,
  `correoInstitucional` NVARCHAR(100) NOT NULL,
  `nombreCompleto` NVARCHAR(200) NOT NULL,
  `numeroTelefonico` NVARCHAR(16) NOT NULL,
  `noPersonal` INT NOT NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ExperienciaEducativa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExperienciaEducativa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ExperienciaEducativa` (
  `idExperienciaEducativa` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(200) NOT NULL,
  `nrc` NVARCHAR(10) NOT NULL,
  `periodo` NVARCHAR(30) NOT NULL,
  `seccion` INT NOT NULL,
  `idDocente` INT NOT NULL,
  PRIMARY KEY (`idExperienciaEducativa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FirmaDigital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FirmaDigital` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FirmaDigital` (
  `idFirmaDigital` INT NOT NULL AUTO_INCREMENT,
  `firma` LONGBLOB NOT NULL,
  PRIMARY KEY (`idFirmaDigital`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Participante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Participante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Participante` (
  `idParticipante` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` NVARCHAR(200) NOT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Periodo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `fechaFin` DATETIME NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `periodo` NVARCHAR(80) NOT NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB
COMMENT = '			';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PersonalAdministrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonalAdministrativo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PersonalAdministrativo` (
  `idPersonalAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` NVARCHAR(50) NOT NULL,
  `usuario` NVARCHAR(50) NOT NULL,
  `correoInstitucional` NVARCHAR(100) NOT NULL,
  `nombreCompleto` NVARCHAR(200) NOT NULL,
  `numeroTelefonico` NVARCHAR(16) NOT NULL,
  PRIMARY KEY (`idPersonalAdministrativo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabajo` (
  `idTrabajo` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(200) NOT NULL,
  PRIMARY KEY (`idTrabajo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TrabajoDocente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrabajoDocente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TrabajoDocente` (
  `idTrabajo` INT NOT NULL,
  `idDocente` INT NOT NULL,
  PRIMARY KEY (`idTrabajo`, `idDocente`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
